name: synapse_link_example
description: An enterprise-grade ToDo app demonstrating SynapseLink capabilities.
publish_to: 'none' # This ensures we don't accidentally publish the example itself
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # The library itself
  synapse_link:
    path: ../ # Points to the local library
  
  # Dependencies needed for the app
  uuid: ^4.5.1
  provider: ^6.1.2
  dio: ^5.7.0
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
