name: synapse_link
description: A professional offline-first sync library for Flutter, bridging local storage and remote APIs with real-time consistency. 
version: 1.0.2
homepage: https://github.com/wisamidis/synapse-links


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^6.2.0
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  uuid: ^4.5.1
  workmanager: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
